/* This code is autogenerated, don't edit it directely */

#ifndef __SDK_C__
#define __SDK_C__

#include <curl/curl.h>

struct osc_str {
	int len;
	char *buf;
};

#define OSC_ENV_FREE_AK_SK 1

struct osc_env {
	char *ak;
	char *sk;
	char *region;
	int flag;
	struct curl_slist *headers;
	struct osc_str endpoint;
	CURL *c;
};

#define OSC_VERBOSE_MODE 1
#define OSC_INSECURE_MODE 2

____args____

int osc_load_ak_sk_from_conf(const char *profile, char **ak, char **sk);

void osc_init_str(struct osc_str *r);
void osc_deinit_str(struct osc_str *r);
int osc_init_sdk(struct osc_env *e, const char *profile, unsigned int flag);
void osc_deinit_sdk(struct osc_env *e);
const char *osc_find_description(const char *call_name);

____functions_proto____

#endif /* __SDK_C__ */
