#!/bin/bash

for opt in "$@"
do
    if [ "${opt}" == "--bash-completion" ]; then
	cat "${APPDIR}/usr/bin/cognac-completion.bash"
        exit 0
    fi
done

export COGNAC_HELP_APPEND="$(echo -en '\t--bash-completion\tprint bash completion(appimage only)\n')"

LD_LIBRARY_PATH=${APPDIR}/usr/lib/ "${APPDIR}/usr/bin/cognac" "$@"
