name: Generate source on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: chrisdickinson/setup-yq@v1.0.0

    - name: configure
      run: ./configure.sh --wget-json-search --yq-go

    - name: make
      run: |
        make main.c osc_sdk.c osc_sdk.h cognac-completion.bash
        tar c osc_sdk.c osc_sdk.h main.c cognac-completion.bash > build-src.tar

    - uses: "actions/upload-artifact@v2"
      with:
          name: sources
          path: build-src.tar
